const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //admin
    GET_DATA_GENDER_AND_ROLE: 'GET_DATA_GENDER_AND_ROLE',
    GET_DATA_GENDER_AND_ROLE_SUCCESS: 'GET_DATA_GENDER_AND_ROLE_SUCCESS',
    GET_DATA_GENDER_AND_ROLE_FAILED: 'GET_DATA_GENDER_AND_ROLE_FAILED',

    SAVE_DATA_MANAGE_USER: 'SAVE_DATA_MANAGE_USER',
    SAVE_DATA_MANAGE_USER_SUCCESS: 'SAVE_DATA_MANAGE_USER_SUCCESS',
    SAVE_DATA_MANAGE_USER_FAILED: 'SAVE_DATA_MANAGE_USER_FAILED',

    // update user
    UPDATE_DATA_USERS_SUCCESS: 'UPDATE_DATA_USERS_SUCCESS',
    UPDATE_DATA_USERS_FAILED: 'UPDATE_DATA_USERS_FAILED',

    // delete user
    DELETE_DATA_USERS_SUCCESS: 'DELETE_DATA_USERS_SUCCESS',
    DELETE_DATA_USERS_FAILED: 'DELETE_DATA_USERS_FAILED',

    GET_DATA_ACTIVE: 'GET_DATA_ACTIVE',
    GET_DATA_ACTIVE_SUCCESS: 'GET_DATA_ACTIVE_SUCCESS',
    GET_DATA_ACTIVE_FAILED: 'GET_DATA_ACTIVE_FAILED',

    SAVE_DATA_CATEGORIES_SUCCESS: 'SAVE_DATA_CATEGORIES_SUCCESS',
    SAVE_DATA_CATEGORIES_FAILED: 'SAVE_DATA_CATEGORIES_FAILED',


    GET_DATA_CATEGORIES_SUCCESS: 'GET_DATA_CATEGORIES_SUCCESS',
    GET_DATA_CATEGORIES_FAILED: 'GET_DATA_CATEGORIES_FAILED',

    GET_DATA_CATEGORIES_SUCCESS_BY_ID: 'GET_DATA_CATEGORIES_SUCCESS_BY_ID',
    GET_DATA_CATEGORIES_FAILED_BY_ID: 'GET_DATA_CATEGORIES_FAILED_BY_ID',

    // update categories
    UPDATE_DATA_CATEGORIES_SUCCESS: 'UPDATE_DATA_CATEGORIES_SUCCESS',
    UPDATE_DATA_CATEGORIES_FAILED: 'UPDATE_DATA_CATEGORIES_FAILED',

    GET_ALL_DATA_USER_SUCCESS: 'GET_ALL_DATA_USER_SUCCESS',
    GET_ALL_DATA_USER_FAILED: 'GET_ALL_DATA_USER_FAILED',


    GET_DATA_USER_BY_ID_SUCCESS: 'GET_DATA_USER_BY_ID_SUCCESS',
    GET_DATA_USER_BY_ID_FAILED: 'GET_DATA_USER_BY_ID_FAILED',

    DELETE_DATA_CATEGORIES_SUCCESS: 'DELETE_DATA_CATEGORIES_SUCCESS',
    DELETE_DATA_CATEGORIES_FAILED: 'DELETE_DATA_CATEGORIES_FAILED',


    GET_DATA_DISCOUNT_COLOR_LAST_SUCCESS: 'GET_DATA_DISCOUNT_COLOR_LAST_SUCCESS',
    GET_DATA_DISCOUNT_COLOR_LAST_FAILED: 'GET_DATA_DISCOUNT_COLOR_LAST_FAILED',

    SAVE_DATA_PRODUCT_SUCCESS: 'SAVE_DATA_PRODUCT_SUCCESS',
    SAVE_DATA_PRODUCT_FAILED: 'SAVE_DATA_PRODUCT_FAILED',

    GET_DATA_PRODUCT_SUCCESS: 'GET_DATA_PRODUCT_SUCCESS',
    GET_DATA_PRODUCT_FAILED: 'GET_DATA_PRODUCT_FAILED',

    GET_DATA_COLOR_PRODUCT_SUCCESS: 'GET_DATA_COLOR_PRODUCT_SUCCESS',
    GET_DATA_COLOR_PRODUCT_FAILED: 'GET_DATA_COLOR_PRODUCT_FAILED',

    SAVE_DATA_IMAGE_PRODUCT_SUCCESS: 'SAVE_DATA_IMAGE_PRODUCT_SUCCESS',
    SAVE_DATA_IMAGE_PRODUCT_FAILED: 'SAVE_DATA_IMAGE_PRODUCT_FAILED',

    GET_DATA_IMAGE_PRODUCT_SUCCESS: 'GET_DATA_IMAGE_PRODUCT_SUCCESS',
    GET_DATA_IMAGE_PRODUCT_FAILED: 'GET_DATA_IMAGE_PRODUCT_FAILED',

    GET_ALL_DATA_CATEGORIES_PRODUCT_SUCCESS: 'GET_ALL_DATA_CATEGORIES_PRODUCT_SUCCESS',
    GET_ALL_DATA_CATEGORIES_PRODUCT_FAILED: 'GET_ALL_DATA_CATEGORIES_PRODUCT_FAILED',

    GET_ALL_DATA_CATEGORIES_PRODUCT_BY_ID_SUCCESS: 'GET_ALL_DATA_CATEGORIES_PRODUCT_BY_ID_SUCCESS',
    GET_ALL_DATA_CATEGORIES_PRODUCT_BY_ID_FAILED: 'GET_ALL_DATA_CATEGORIES_PRODUCT_BY_ID_FAILED',

    GET_ID_BY_HEX_SUCCESS: 'GET_ID_BY_HEX_SUCCESS',
    GET_ID_BY_HEX_FAILED: 'GET_ID_BY_HEX_FAILED',

    GET_ALL_DATA_PRODUCT_BY_COLOR_SUCCESS: 'GET_ALL_DATA_PRODUCT_BY_COLOR_SUCCESS',
    GET_ALL_DATA_PRODUCT_BY_COLOR_FAILED: 'GET_ALL_DATA_PRODUCT_BY_COLOR_FAILED',


    SAVE_DATA_MARKDOWN_SUCCESS: 'SAVE_DATA_MARKDOWN_SUCCESS',
    SAVE_DATA_MARKDOWN_SUCCESS_FAILED: 'SAVE_DATA_MARKDOWN_SUCCESS_FAILED',

    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILED: 'ADD_TO_CART_FAILED',

    SHOW_ALL_DATA_BY_USER_ID_SUCCESS: 'SHOW_ALL_DATA_BY_USER_ID_SUCCESS',
    SHOW_ALL_DATA_BY_USER_ID_FAILED: 'SHOW_ALL_DATA_BY_USER_ID_FAILED',

    PLUS_DATA_CART_SUCCESS: 'PLUS_DATA_CART_SUCCESS',
    PLUS_DATA_CART_FAILED: 'PLUS_DATA_CART_FAILED',

    MINUS_DATA_CART_SUCCESS: 'MINUS_DATA_CART_SUCCESS',
    MINUS_DATA_CART_FAILED: 'MINUS_DATA_CART_FAILED',

    DELETE_BY_ID_DATA_CART_SUCCESS: 'DELETE_BY_ID_DATA_CART_SUCCESS',
    DELETE_BY_ID_DATA_CART_FAILED: 'DELETE_BY_ID_DATA_CART_FAILED',

    PATIENT_BOOKING_SUCCESS: 'PATIENT_BOOKING_SUCCESS',
    PATIENT_BOOKING_FAILED: 'PATIENT_BOOKING_FAILED',

    GET_ALL_DATA_PRICE_ALLCODE_SUCCESS: 'GET_ALL_DATA_PRICE_ALLCODE_SUCCESS',
    GET_ALL_DATA_PRICE_ALLCODE_FAILED: 'GET_ALL_DATA_PRICE_ALLCODE_FAILED',

    GET_DATA_YML_SUCCESS: 'GET_DATA_YML_SUCCESS',
    GET_DATA_YML_FAILED: 'GET_DATA_YML_FAILED',

    DELETE_DATA_PRODUCT_ID_SUCCESS: 'DELETE_DATA_PRODUCT_ID_SUCCESS',
    DELETE_DATA_PRODUCT_ID_FAILED: 'DELETE_DATA_PRODUCT_ID_FAILED',

    UPDATE_DATA_PRODUCT_ID_SUCCESS: 'UPDATE_DATA_PRODUCT_ID_SUCCESS',
    UPDATE_DATA_PRODUCT_ID_FAILED: 'UPDATE_DATA_PRODUCT_ID_FAILED',


    UPDATE_DATA_IMAGE_ID_SUCCESS: 'UPDATE_DATA_IMAGE_ID_SUCCESS',
    UPDATE_DATA_IMAGE_ID_FAILED: 'UPDATE_DATA_IMAGE_ID_FAILED',

    UPDATE_DATA_COLOR_ID_SUCCESS: 'UPDATE_DATA_COLOR_ID_SUCCESS',
    UPDATE_DATA_COLOR_ID_FAILED: 'UPDATE_DATA_COLOR_ID_FAILED',

    DELETE_DATA_COLOR_ID_SUCCESS: 'DELETE_DATA_COLOR_ID_SUCCESS',
    DELETE_DATA_COLOR_ID_FAILED: 'DELETE_DATA_COLOR_ID_FAILED',

    DELETE_DATA_IMAGE_ID_SUCCESS: 'DELETE_DATA_IMAGE_ID_SUCCESS',
    DELETE_DATA_IMAGE_ID_FAILED: 'DELETE_DATA_IMAGE_ID_FAILED',







    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT'

})

export default actionTypes;